var songsList = [
{nombre:'(Just Like) Starting Over',artista:'John Lennon',anio:'1980',yt:'mIVq0_LD6a0'},
{nombre:'(Rap) Superstar',artista:'Cypress Hill',anio:'2000',yt:'C7D27mL2JkI'},
{nombre:'(Rock) Superstar',artista:'Cypress Hill',anio:'2000',yt:'W4VpE-0zitU'},
{nombre:'¿Dónde Están?',artista:'Sentidos Opuestos',anio:'2012',yt:'MQW0w82vHt8'},
{nombre:'19-2000',artista:'Gorillaz',anio:'2001',yt:'Tq7Ovshz1UI'},
{nombre:'1979',artista:'The Smashing Pumpkins',anio:'1995',yt:'4aeETEoNfOg'},
{nombre:'7 Seconds',artista:'Youssou N\'Dour Feat. Neneh Cherry',anio:'1994',yt:'wqCpjFMvz-k'},
{nombre:'9PM',artista:'ATB',anio:'1999',yt:'ri6Efk1SPJc'},
{nombre:'Acapulco 78',artista:'Fase',anio:'2002',yt:'MZFIQVNJ9ns'},
{nombre:'Adelante',artista:'Sash',anio:'2000',yt:'gFw2or20r2A'},
{nombre:'Adventure Of A Lifetime',artista:'Coldplay',anio:'2015',yt:'QtXby3twMmI'},
{nombre:'Afroman',artista:'Plastilina Mosh',anio:'1998',yt:'6anAOpoBh2o'},
{nombre:'Afuera',artista:'Caifanes',anio:'1994',yt:'Gv6gOSLgVD4'},
{nombre:'Ain’t Nobody',artista:'Felix Jaehn Feat. Jasmine Thompson',anio:'2016',yt:'BW91OY3wVoo'},
{nombre:'All By MySelf',artista:'Eric Carmen',anio:'1975',yt:'e4VQzsRA4as'},
{nombre:'All Good Things Come To An End',artista:'Nelly Furtado',anio:'2006',yt:'4pBo-GL9SRg'},
{nombre:'All The Lovers',artista:'Kylie Minogue',anio:'2010',yt:'frv6FOt1BNI'},
{nombre:'All The Small Things',artista:'Blink 182',anio:'1999',yt:'9Ht5RZpzPqw'},
{nombre:'All These Things That I\'ve Done',artista:'The Killers',anio:'2004',yt:'sZTpLvsYYHw'},
{nombre:'Almost Home',artista:'Moby Feat. Damien Jurado',anio:'2013',yt:'QVbD9lKVszE'},
{nombre:'Almost Home (Vijay & Sofia Zlatko Remix)',artista:'Moby',anio:'????',yt:'-kdmGPvZQuo'},
{nombre:'Alone',artista:'Alan Walker',anio:'2016',yt:'1-xGerv5FOk'},
{nombre:'Alors On Danse',artista:'Stromae',anio:'2010',yt:'VHoT4N43jK8'},
{nombre:'Alright',artista:'Supergrass',anio:'1995',yt:'fwjXgskUN50'},
{nombre:'American Boy',artista:'Estelle',anio:'2008',yt:'Ic5vxw3eijY'},
{nombre:'Amerika',artista:'Rammstein',anio:'2004',yt:'Rr8ljRgcJNM'},
{nombre:'Ammo',artista:'D-Wayne',anio:'2013',yt:'eUV4AkKVLTQ'},
{nombre:'An Honest Mistake',artista:'The Bravery',anio:'2005',yt:'O8vzbezVru4'},
{nombre:'Analyse',artista:'Cranberries',anio:'2001',yt:'DaBWlBknNgs'},
{nombre:'And I Was A Boy From School',artista:'Hot Chip',anio:'2006',yt:'X-fu1PQWTBk'},
{nombre:'And We Danced',artista:'Macklemore x Ryan Lewis',anio:'2009',yt:'Vhf5cuXiLTA'},
{nombre:'Another Chance',artista:'Roger Sánchez',anio:'2001',yt:'ecWZpYX-aKg'},
{nombre:'Anthem',artista:'Alesso',anio:'2017',yt:'XwjJ5RTKWR4'},
{nombre:'Antología',artista:'Shakira',anio:'1995',yt:'IK3jNLfTEdw'},
{nombre:'Aquí Estoy',artista:'Blanca & Kermit',anio:'????',yt:'Aj7XeCztAnA'},
{nombre:'Are You With Me?',artista:'Lost Frequencies',anio:'2014',yt:'VjHMDlAPMUw'},
{nombre:'Así Es La Vida',artista:'Elefante',anio:'2001',yt:'Xq_Ltv74nUQ'},
{nombre:'Ass Like That',artista:'Eminem',anio:'2004',yt:'um4-d7VzZiE'},
{nombre:'Atomic',artista:'Blondie',anio:'1979',yt:'1Tko1G6XRiQ'},
{nombre:'Automatic',artista:'ZHU x AlunaGeorge',anio:'2015',yt:'QhGN7_Z-AN0'},
{nombre:'Ayami Bik',artista:'DJ Samy ft. Elissa',anio:'????',yt:'-ZA2lN7CRoc'},
{nombre:'B.Y.O.B.',artista:'System Of A Down',anio:'2005',yt:'zUzd9KyIDrM'},
{nombre:'Back To Black',artista:'Amy Winehouse',anio:'2006',yt:'TJAfLE39ZZ8'},
{nombre:'Bad Girls',artista:'M.I.A.',anio:'2010',yt:'2uYs0gJD-LE'},
{nombre:'Bad To The Bone',artista:'George Thorogood',anio:'1982',yt:'_7VsoxT_FUY'},
{nombre:'Bailando',artista:'Paradisio',anio:'1997',yt:'xiWtqVtd1Oo'},
{nombre:'Baker Street',artista:'Michael Mind',anio:'2008',yt:'SGuP7A4cwzA'},
{nombre:'Bang My Head',artista:'David Guetta Feat. Sia & Fetty Wap',anio:'2014',yt:'qqjVwAg5fK4'},
{nombre:'Bat Country',artista:'Avenged Sevenfold',anio:'2005',yt:'IHS3qJdxefY'},
{nombre:'Be Mine',artista:'Ofenbach',anio:'2016',yt:'oNWOC_Pvo4w'},
{nombre:'Be Yourself',artista:'Audioslave',anio:'2005',yt:'WC5FdFlUcl0'},
{nombre:'Beautiful',artista:'Moby',anio:'2005',yt:'Hv11q8Ss1V8'},
{nombre:'Beautiful Day',artista:'U2',anio:'2000',yt:'co6WMzDOh1o'},
{nombre:'Beautiful Girls',artista:'Sean Kingston',anio:'2007',yt:'MrTz5xjmso4'},
{nombre:'Beautiful Way',artista:'Beck',anio:'1999',yt:'wQS9_ei66Co'},
{nombre:'Because I Got High',artista:'Afroman',anio:'2000',yt:'WeYsTmIzjkw'},
{nombre:'Becoming Insane',artista:'Infected Mushroom',anio:'2007',yt:'RUJ75jeTQ1A'},
{nombre:'Behind Blue Eyes',artista:'Limp Bizkit',anio:'2003',yt:'Tr8uesBowS4'},
{nombre:'Believe',artista:'Chemical Brothers',anio:'2005',yt:'_UkWcXizRwU'},
{nombre:'Believe',artista:'Cher',anio:'1998',yt:'5Uu3kCEEc98'},
{nombre:'Best Day Of My Life',artista:'American Authors',anio:'2014',yt:'Y66j_BUCBMY'},
{nombre:'Between Angels And Insects',artista:'Papa Roach',anio:'2000',yt:'H2jCbXiEQI4'},
{nombre:'Big Big World',artista:'Emilia',anio:'1998',yt:'wpkS2DU_qMs'},
{nombre:'Bigger Than Love',artista:'ilan Bluestone feat. Giuseppe De Luca',anio:'2015',yt:'U39N6KtAxMQ'},
{nombre:'Bittersweet Symphony',artista:'The Verve',anio:'1997',yt:'1lyu1KKwC74'},
{nombre:'Black is Black',artista:'Los Bravos',anio:'1966',yt:'aGeFf_rIAVQ'},
{nombre:'Black Magic Woman',artista:'Carlos Santana',anio:'1993',yt:'IPo9Gd2z6rI'},
{nombre:'Black Or White',artista:'Michael Jackson',anio:'1991',yt:'F2AitTPI5U0'},
{nombre:'Blame',artista:'Calvin Harris Feat. John Newman',anio:'2014',yt:'6ACl8s_tBzE'},
{nombre:'Blaze Of Glory',artista:'Jon Bon Jovi',anio:'1990',yt:'MfmYCM4CS8o'},
{nombre:'Bleed It Out',artista:'Linkin Park',anio:'2007',yt:'OnuuYcqhzCE'},
{nombre:'Blow Me (One Last Kiss)',artista:'P!nk',anio:'2012',yt:'3jNlIGDRkvQ'},
{nombre:'Blurred Lines',artista:'Robin Thicke Feat. T.I. & Pharrell',anio:'2013',yt:'yyDUC1LUXSU'},
{nombre:'Bomba',artista:'Jessy Matador',anio:'2010',yt:'8boNhR297Ck'},
{nombre:'Booyah',artista:'Showtek Feat. We Are Loud & Sonny Wilson',anio:'2014',yt:'QCyIY10KBnk'},
{nombre:'Born Slippy',artista:'Underworld',anio:'2000',yt:'6iKFn8dlxX8'},
{nombre:'Bright Lights Bigger City',artista:'Cee Lo Green',anio:'2010',yt:'UBhdIcb84Hw'},
{nombre:'Brother Louie \'98',artista:'Modern Talking',anio:'1998',yt:'K5DALXwOe0s'},
{nombre:'Bulletproof',artista:'La Roux',anio:'2009',yt:'Kk8eJh4i8Lo'},
{nombre:'Bullit',artista:'Watermät',anio:'2009',yt:'HoMzLLWNV1g'},
{nombre:'Burn It Down',artista:'Linkin Park',anio:'2012',yt:'dxytyRy-O1k'},
{nombre:'Burn The Disco',artista:'Felix da Housecat Feat. will.i.am',anio:'2012',yt:'Bu_kdN0RakE'},
{nombre:'Bury It',artista:'CHVRCHES Feat. Hayley Williams',anio:'2015',yt:'B9BLMNn0PrQ'},
{nombre:'Butterfly',artista:'Crazy Town',anio:'1999',yt:'6FEDrU85FLE'},
{nombre:'By The Way',artista:'Red Hot Chili Peppers',anio:'2002',yt:'JnfyjwChuNU'},
{nombre:'Californian Knight',artista:'Platinum Doug',anio:'2015',yt:'2bf0z01un8s'},
{nombre:'Californication',artista:'Red Hot Chili Peppers',anio:'1999',yt:'YlUKcNNmywk'},
{nombre:'Call To Arms',artista:'Classroom Battles',anio:'????',yt:'G5_xd-_Yiqs'},
{nombre:'Canon in D',artista:'Pachelbel',anio:'1680',yt:'JvNQLJ1_HQ0'},
{nombre:'Can\'t Get You Out of My Head',artista:'Kylie Minogue',anio:'2001',yt:'YPwtJ89jes4'},
{nombre:'Can\'t Stop',artista:'Red Hot Chili Peppers',anio:'2002',yt:'8DyziWtkfBw'},
{nombre:'Can\'t Take My Eyes Off Of You',artista:'Boys Town Gang',anio:'1982',yt:'GWHZxXuJFzw'},
{nombre:'Can\'t Take My Eyes Off Of You',artista:'Frankie Vallie',anio:'1967',yt:'R1j1RRWcYSg'},
{nombre:'Careless Whisper',artista:'Wham',anio:'1984',yt:'CDKn5BGTGMM'},
{nombre:'Celebrate',artista:'Zhi-Vago',anio:'1996',yt:'bh-oLNGL0fM'},
{nombre:'Celebrate Life',artista:'Eelke Kleijn',anio:'2015',yt:'qxOdiBTg7o8'},
{nombre:'Chained To The Rhythm',artista:'Katy Perry Feat. Skip Marley',anio:'2017',yt:'Um7pMggPnug'},
{nombre:'Chandelier',artista:'Sia',anio:'2014',yt:'2vjPBrBU-TM'},
{nombre:'Changes',artista:'Faul & Wad Ad vs. Pnau',anio:'2014',yt:'6_tyPKUZumw'},
{nombre:'Charly Black',artista:'Gyal You A Party Animal',anio:'2016',yt:'xPeIm20TYjI'},
{nombre:'Chasing Cars',artista:'Snow Patrol',anio:'2006',yt:'GemKqzILV4w'},
{nombre:'Chica de Humo',artista:'Emmanuel',anio:'1988',yt:'SCE39bYioDU'},
{nombre:'Children',artista:'Robert Miles',anio:'1996',yt:'6QEPrDBMqJ0'},
{nombre:'Chocolate',artista:'Kylie Minogue',anio:'2003',yt:'WjhmB0JlCTo'},
{nombre:'Chop Suey!',artista:'System Of A Down',anio:'2001',yt:'CSvFpBOe8eY'},
{nombre:'Ciega, Sordomuda',artista:'Shakira',anio:'1998',yt:'B3gbisdtJnA'},
{nombre:'Cinderella (She Said Her Name)',artista:'Bob Sinclar',anio:'2013',yt:'idr01rpcSfM'},
{nombre:'Clint Eastwood',artista:'Gorillaz',anio:'2001',yt:'UclCCFNG9q4'},
{nombre:'Clocks',artista:'Buena Vista Social Club',anio:'2006',yt:'onpJ6fLBif8'},
{nombre:'Clocks',artista:'Coldplay',anio:'2002',yt:'d020hcWA_Wg'},
{nombre:'Clocks',artista:'Coldplay (Royksopp Trembling Heart Remix)',anio:'2014',yt:'xjRQvbPh9tQ'},
{nombre:'Closer to Me',artista:'Chab Feat. Jd Davis',anio:'2005',yt:'pauixF-ksxI'},
{nombre:'Club Can\'t Handle Me',artista:'Flo Rida Feat. David Guetta',anio:'2010',yt:'SgM3r8xKfGE'},
{nombre:'Cocaine Model',artista:'ZHU',anio:'2014',yt:'ThUtI7LB17Y'},
{nombre:'Colors',artista:'Halsey',anio:'2015',yt:'JGulAZnnTKA'},
{nombre:'Come And Get It',artista:'John Newman',anio:'2015',yt:'I5exsScaHWo'},
{nombre:'Come Into My World',artista:'Kylie Minogue',anio:'2001',yt:'Bl-vtVuimZo'},
{nombre:'Come Undone',artista:'Duran Duran',anio:'1993',yt:'ICnlyNUt_0o'},
{nombre:'Come With Me',artista:'Puff Daddy',anio:'1998',yt:'rxuodY-c0yU'},
{nombre:'Con Todos Menos Conmigo',artista:'Timbiriche',anio:'1987',yt:'vBjkeuYEGPA'},
{nombre:'Connected',artista:'Stereo MC',anio:'1992',yt:'Qm8ClRnVxtE'},
{nombre:'Conteo',artista:'Don Omar',anio:'2006',yt:'AypCssLHs4A'},
{nombre:'Cool for the Summer',artista:'Demi Lovato',anio:'2015',yt:'il9nqWw9W3Y'},
{nombre:'Cosa Más Bella',artista:'Eros Ramazzotti',anio:'1996',yt:'UojBaKX5Vz4'},
{nombre:'Cotton Fields',artista:'Creedence Clearwater Revival',anio:'1969',yt:'C4zPEmRufMU'},
{nombre:'Counting Stars',artista:'OneRepublic',anio:'2013',yt:'hT_nvWreIhg'},
{nombre:'Cowboy',artista:'Kid Rock',anio:'1998',yt:'glb2U6y-GdU'},
{nombre:'Crawling',artista:'Linkin Park',anio:'2000',yt:'Gd9OhYroLN0'},
{nombre:'Crazy',artista:'Gnarls Barkley',anio:'2006',yt:'Qe500eIK1oA'},
{nombre:'Crazy',artista:'TEEMID Feat. Joie Tan',anio:'2014',yt:'qXHUpqdnwfE'},
{nombre:'Crazy (James Michael Mix)',artista:'Alanis Morissette',anio:'2006',yt:'IaiVNtsPV5I'},
{nombre:'Cry For You',artista:'September',anio:'2005',yt:'pxu6iQ28arw'},
{nombre:'Dance 4 Life',artista:'Tiësto Feat. Maxi Jazz',anio:'2007',yt:'mskjDQAfksc'},
{nombre:'Dance Floor Anthem',artista:'Good Charlotte',anio:'2007',yt:'_Pjs-QkjmkM'},
{nombre:'Dani California',artista:'Red Hot Chili Peppers',anio:'2006',yt:'Sb5aq5HcS1A'},
{nombre:'Dare',artista:'Gorillaz',anio:'2005',yt:'uAOR6ib95kQ'},
{nombre:'Days Go By',artista:'Dirty Vegas',anio:'2002',yt:'D0eNHu3BlRI'},
{nombre:'De La Noche A La Mañana',artista:'Elefante',anio:'2001',yt:'-r2-cvj7h3M'},
{nombre:'Demasiado Corazón',artista:'Willie Colón',anio:'1998',yt:'aYkMX6TUS08'},
{nombre:'Der Tag (Du Bist Erwacht)',artista:'Schiller Feat. Jette Von Roth',anio:'2005',yt:'r1SBknR5ma4'},
{nombre:'Desesperada',artista:'Marta Sánchez',anio:'1993',yt:'d3fXmjU3DSY'},
{nombre:'Destroy Everything You Touch',artista:'Ladytron',anio:'2005',yt:'fPZoaGqLGpQ'},
{nombre:'Difacil Rap',artista:'Bravo & DJ\'s',anio:'2009',yt:'2FDdJYtGems'},
{nombre:'Dirty Work',artista:'Austin Mahone',anio:'2015',yt:'CX-un4obyU0'},
{nombre:'Disco 2000',artista:'Pulp',anio:'1995',yt:'qJS3xnD7Mus'},
{nombre:'Disco Samba',artista:'Two Man Sound',anio:'1977',yt:'IHKl63d-TfM'},
{nombre:'Disfruto',artista:'Carla Morrison',anio:'2012',yt:'_ruEj-XK1lA'},
{nombre:'Do The Rave Stomp',artista:'DJ Dero',anio:'1993',yt:'lE5Is6XwEiM'},
{nombre:'Doesn\'t Really Matter',artista:'Janet Jackson',anio:'2000',yt:'7iJZosBX2L0'},
{nombre:'Dog Days Are Over',artista:'Florence + The Machine',anio:'2009',yt:'iWOyfLBYtuU'},
{nombre:'Doin\' Dirt',artista:'Maroon 5',anio:'2011',yt:'u95StS-Ez_w'},
{nombre:'Don\'t Be So Shy',artista:'Imany (Filatov & Karas Remix)',anio:'2014',yt:'b1_B-IKEufg'},
{nombre:'Don\'t Cha',artista:'Pussycat Dolls, Ralphi Rosario',anio:'????',yt:'kpm3cB4HR5A'},
{nombre:'Don\'t Let Me Get Me',artista:'P!nk',anio:'2000',yt:'asaCQOZpqUQ'},
{nombre:'Don\'t Lie',artista:'Black Eyed Peas',anio:'2004',yt:'WbJNkH-pDd8'},
{nombre:'Don\'t Mind',artista:'Kent Jones',anio:'2016',yt:'n49qi-dU9IE'},
{nombre:'Don\'t Phunk With My Heart',artista:'Black Eyed Peas',anio:'2004',yt:'P4Bda6_usuc'},
{nombre:'Just Can\'t Get Enough',artista:'Depeche Mode',anio:'1981',yt:'_6FBfAQ-NDE'},
{nombre:'Don\'t Stop Movin\'',artista:'S Club 7',anio:'2001',yt:'vm262cXxRrU'},
{nombre:'Don\'t Stop The Music',artista:'Rihanna',anio:'2007',yt:'yd8jh9QYfEs'},
{nombre:'Don\'t Stop The Party',artista:'Black Eyed Peas',anio:'2009',yt:'u9LH_y159sg'},
{nombre:'Don\'t Worry',artista:'Madcon Feat. Ray Dalton',anio:'2015',yt:'qlPx6tmAIlM'},
{nombre:'Dont Worry, Be Happy',artista:'Bobby McFerrin',anio:'1988',yt:'d-diB65scQU'},
{nombre:'Don\'t You Know',artista:'Kungs Feat. Jamie N Commons',anio:'2016',yt:'Nf-FLiO4p3c'},
{nombre:'Dosis Perfecta',artista:'Panteón Rococco',anio:'1999',yt:'o0H2IZLc9dY'},
{nombre:'DosPuntoCero',artista:'DaPuntoBeat',anio:'2010',yt:'NxkhFuXPWT4'},
{nombre:'Dreamland',artista:'DJ Ross',anio:'2002',yt:'c_Dxd0keXyk'},
{nombre:'Dreams',artista:'Cranberries',anio:'1993',yt:'Yam5uK6e-bQ'},
{nombre:'Drive By',artista:'Train',anio:'2012',yt:'oxqnFJ3lp5k'},
{nombre:'Drop That Low',artista:'Tujamo',anio:'2016',yt:'souJM4aCk6w'},
{nombre:'Du Hast',artista:'Rammstein',anio:'1997',yt:'W3q8Od5qJio'},
{nombre:'Dust in the Wind',artista:'Kansas',anio:'1977',yt:'tH2w6Oxx0kQ'},
{nombre:'Easy Love',artista:'Sigala',anio:'2015',yt:'ozx898ADTxM'},
{nombre:'El Ritmo De La Marimba',artista:'DJ Kuri',anio:'2004',yt:'-QinMJmr12I'},
{nombre:'Elektro',artista:'Outwork Feat. Mr Gee',anio:'2006',yt:'bSZ6wl7NTlM'},
{nombre:'Engel',artista:'Rammstein',anio:'1997',yt:'x2rQzv8OWEY'},
{nombre:'English Summer Rain',artista:'Placebo',anio:'2003',yt:'5YGpwSrSqgs'},
{nombre:'Enjoy The Silence',artista:'Depeche Mode',anio:'1990',yt:'m0AKJMGxwpE'},
{nombre:'E-Pro',artista:'Beck',anio:'2005',yt:'RIrG6xBW5Wk'},
{nombre:'Europa',artista:'Carlos Santana',anio:'1976',yt:'Ot6pSrKT1oc'},
{nombre:'Every Car You Chase',artista:'Snow Patrol vs. The Police',anio:'2007',yt:'wvb4GgyDdr0'},
{nombre:'Everybody\'s Changing',artista:'Keane',anio:'2003',yt:'Zx4Hjq6KwO0'},
{nombre:'Everyday',artista:'Carly Comando',anio:'2006',yt:'RCObXuAwCIA'},
{nombre:'Extreme Ways',artista:'Moby',anio:'2002',yt:'VTIkDmNVJeA'},
{nombre:'Face',artista:'Beck Mongolian Chop Squad',anio:'????',yt:'lqpIsRvIhBk'},
{nombre:'Faded',artista:'Alan Walker',anio:'2015',yt:'60ItHLz5WEA'},
{nombre:'Faded',artista:'ZHU',anio:'2014',yt:'zk3r-K8TQ5g'},
{nombre:'Fashionista',artista:'Jimmy James',anio:'2006',yt:'XnF4eGSpeYA'},
{nombre:'Faster Kill Pussycat',artista:'Paul Oakenfold Feat. Brittany Murphy',anio:'2006',yt:'gyTPfifzqjo'},
{nombre:'Feel',artista:'Robbie Williams',anio:'2002',yt:'iy4mXZN1Zzk'},
{nombre:'Feel Good Inc.',artista:'Gorillaz',anio:'2005',yt:'HyHNuVaZJ-k'},
{nombre:'Feel It',artista:'The Tamperer Feat. Maya',anio:'1998',yt:'Ht-m4vMWRqA'},
{nombre:'Feel So Close',artista:'Calvin Harris',anio:'2012',yt:'dGghkjpNCQ8'},
{nombre:'Feel The Beat',artista:'Darude',anio:'2001',yt:'mN84To5ndw0'},
{nombre:'Feel The Love',artista:'Rudimental Feat. John Newman',anio:'2012',yt:'oABEGc8Dus0'},
{nombre:'Feels Good',artista:'Robert Rodriguez',anio:'2015',yt:'d0eKZnvtbUs'},
{nombre:'Fernando',artista:'Abba',anio:'1980',yt:'dQsjAbZDx-4'},
{nombre:'First Day',artista:'Timo Maas Feat. Brian Molko',anio:'2005',yt:'xdpcjtRW2jY'},
{nombre:'First Time',artista:'Markus Schulz Feat. Anita Kelsey',anio:'2005',yt:'E2sUs-KbxXY'},
{nombre:'Five Hours',artista:'Deorro x Chris Brown',anio:'2015',yt:'j3CaHeakZF4'},
{nombre:'Flame (Chicken Lips Remix)',artista:'Bell X1',anio:'????',yt:'rl7JpfMXI1k'},
{nombre:'Flight 643',artista:'Tiësto',anio:'2001',yt:'Gdy01EjU7vg'},
{nombre:'Float On',artista:'Modest Mouse',anio:'2004',yt:'CTAud5O7Qqk'},
{nombre:'Flying To Mercury',artista:'DiDuLa',anio:'????',yt:'xHHI22a81Wg'},
{nombre:'Free',artista:'Ultra Naté',anio:'1998',yt:'230VadxFFok'},
{nombre:'Freedom To Love',artista:'Lexter',anio:'2008',yt:'V8HlSo45NnY'},
{nombre:'Frozen',artista:'Madonna',anio:'1998',yt:'evxEOXkxRIA'},
{nombre:'Fruta Fresca',artista:'Carlos Vives',anio:'1999',yt:'K8g0KGIsHGs'},
{nombre:'Fuck With You',artista:'Bob Sinclar Feat. Sophie Ellis-Bextor & Gilbere Forte',anio:'2012',yt:'wa4FBSI4Q4I'},
{nombre:'Galvanize',artista:'Chemical Brothers',anio:'2005',yt:'Xu3FTEmN-eg'},
{nombre:'Get Over You',artista:'Sophie Ellis-Bextor',anio:'2001',yt:'r72Sbmj2OrM'},
{nombre:'Get Some',artista:'Lykke Li',anio:'2011',yt:'-TTPGAy5H_E'},
{nombre:'Get The Party Started',artista:'P!nk',anio:'2001',yt:'RD6V6HPccbY'},
{nombre:'Gettin\' Over You',artista:'David Guetta',anio:'2009',yt:'hWjrMTWXH28'},
{nombre:'Gimme Tha Power',artista:'Molotov',anio:'1997',yt:'hfmY9Wlxx0o'},
{nombre:'Gimme The Love',artista:'Jake Bugg',anio:'2016',yt:'o70e7Nb8SVM'},
{nombre:'Girls & Boys',artista:'Blur',anio:'1994',yt:'WDswiT87oo8'},
{nombre:'Girls in love',artista:'Andreas Dorau',anio:'1997',yt:'8IBBbj5LyJs'},
{nombre:'Girls In Luv',artista:'Djane HouseKat Feat. Rameez',anio:'2014',yt:'Qn4I4OuDCYA'},
{nombre:'Girls Like',artista:'Tinie Tempah Feat. Zara Larsson',anio:'2017',yt:'OEiva3cMv6k'},
{nombre:'Girls Talk Boys',artista:'5 Seconds of Summer',anio:'1984',yt:'0MXldocLfu4'},
{nombre:'Give It 2 Me',artista:'Madonna',anio:'2008',yt:'aQRLSBUNupg'},
{nombre:'Give It Away',artista:'Red Hot Chili Peppers',anio:'1991',yt:'Mr_uHJPUlO8'},
{nombre:'Give Me Your Love',artista:'Sigala Feat. John Newman & Nile Rodgers',anio:'2016',yt:'ze6H75NCUs8'},
{nombre:'Glad You Came',artista:'The Wanted',anio:'2011',yt:'2ggzxInyzVE'},
{nombre:'Go',artista:'The Chemical Brothers',anio:'2015',yt:'LO2RPDZkY88'},
{nombre:'Go Pato',artista:'Pato Banton',anio:'1992',yt:'jTsl6S1p4yU'},
{nombre:'Go West',artista:'Pet Shop Boys',anio:'1993',yt:'7NZ04BG7TfA'},
{nombre:'God Gave Me Everything',artista:'Mick Jagger Feat. Lenny Kravitz',anio:'2001',yt:'x4eBJKQvpe0'},
{nombre:'Gold Digger',artista:'Kanye West Feat. Jamie Foxx',anio:'2005',yt:'6vwNcNOTVzY'},
{nombre:'Good Grief',artista:'Bastille',anio:'2016',yt:'ZWCB3hpJDXM'},
{nombre:'Goodbye Stranger',artista:'Supertramp',anio:'1979',yt:'1K7S8TFJaYA'},
{nombre:'Goodbye, Horses',artista:'Q Lazzarus',anio:'1988',yt:'X_DVS_303kQ'},
{nombre:'Groovejet (Andrey Exx & Fomichev remix)',artista:'Lissat & Voltaxx Marc Misher',anio:'????',yt:'byy-LT1RTps'},
{nombre:'Groupie',artista:'Bob Sinclar',anio:'2012',yt:'ImCFJqg6rLs'},
{nombre:'Guns For Hands',artista:'Twenty One Pilots',anio:'2011',yt:'Pmv8aQKO6k0'},
{nombre:'Habits',artista:'Tove Lo',anio:'2014',yt:'oh2LWWORoiM'},
{nombre:'Hang Me Up To Dry',artista:'Cold War Kids',anio:'2006',yt:'LrrGKR8Xii4'},
{nombre:'Harder Better Faster Stronger',artista:'Daft Punk',anio:'2001',yt:'gAjR4_CbPpQ'},
{nombre:'Hardest Button To Button',artista:'The White Stripes',anio:'2003',yt:'K4dx42YzQCE'},
{nombre:'Hasta La Piel',artista:'Carla Morrison',anio:'2012',yt:'eih7mFBwCnw'},
{nombre:'Heart Of Glass',artista:'Blondie',anio:'1978',yt:'WGU_4-5RaxU'},
{nombre:'Heart Skips a Beat',artista:'Olly Murs Feat. Rizzle Kicks',anio:'2011',yt:'j5dFe-WKuPs'},
{nombre:'Heaven',artista:'Kasper Bjørke',anio:'2010',yt:'QfJcKlH4T5c'},
{nombre:'Heavy Cross',artista:'Gossip',anio:'2009',yt:'5mQVljB7JGw'},
{nombre:'Here',artista:'HellogoodBye',anio:'2006',yt:'yH0RbHjD4vw'},
{nombre:'Here Comes The Hotstepper',artista:'Ini Kamoze',anio:'1994',yt:'w0N4twV28Mw'},
{nombre:'Here Without You',artista:'3 Doors Down',anio:'2002',yt:'kPBzTxZQG5Q'},
{nombre:'Hey Boy Hey Girl',artista:'Chemical Brothers',anio:'1999',yt:'c8-kj1GkbfU'},
{nombre:'Hey Mama',artista:'Black Eyed Peas',anio:'2003',yt:'rtczBseiAac'},
{nombre:'Hey Ya',artista:'OutKast',anio:'2003',yt:'PWgvGjAhvIw'},
{nombre:'Hideaway',artista:'Kiesza',anio:'2014',yt:'ESXgJ9-H-2U'},
{nombre:'High By The Beach',artista:'Lana Del Rey',anio:'2015',yt:'QnxpHIl5Ynw'},
{nombre:'Higher',artista:'Taio Cruz Feat. Kylie Minogue',anio:'2009',yt:'KRBS5WZMdik'},
{nombre:'Higher And Higher',artista:'Jackie Wilson',anio:'1967',yt:'mzDVaKRApcg'},
{nombre:'History',artista:'Michael Jackson Feat. Le P',anio:'????',yt:'_7abnBfcbj8'},
{nombre:'Hit That',artista:'The Offspring',anio:'2003',yt:'isKj9RnC9NI'},
{nombre:'Hoja En Blanco',artista:'Ismael y Ana',anio:'????',yt:'hmsLquvA4pc'},
{nombre:'Hold On, We\'re Going Home',artista:'Drake',anio:'2013',yt:'GxgqpCdOKak'},
{nombre:'Hollaback Girl',artista:'Gwen Stephany',anio:'2004',yt:'Kgjkth6BRRY'},
{nombre:'Holler',artista:'Spice Girls',anio:'2000',yt:'gFBWbH5CeRE'},
{nombre:'Hometown Girl',artista:'ZHU',anio:'2016',yt:'9rExEf_QKgs'},
{nombre:'Hot',artista:'Inna',anio:'2010',yt:'K15zuILXkP0'},
{nombre:'Hotel California',artista:'The Eagles',anio:'1976',yt:'lrfhf1Gv4Tw'},
{nombre:'Hotline Bling',artista:'Drake',anio:'2016',yt:'uxpDa-c-4Mc'},
{nombre:'Hot-n-Fun',artista:'N.E.R.D.',anio:'2010',yt:'F6ZfA5QZDHY'},
{nombre:'House Of The Rising Sun',artista:'The Animals',anio:'1964',yt:'hRXb7K7k7bQ'},
{nombre:'How Deep Is Your Love',artista:'Calvin Harris & Disciples',anio:'2016',yt:'EgqUJOudrcM'},
{nombre:'How Do You Do',artista:'Mouth & MacNeal',anio:'1971',yt:'6QXyqk9flwk'},
{nombre:'Hung Up',artista:'Madonna',anio:'2005',yt:'EDwb9jOVRtU'},
{nombre:'Hurts',artista:'Emeli Sandé',anio:'2016',yt:'9TqUlGyWSEk'},
{nombre:'I Believe In You',artista:'Kylie Minogue',anio:'2004',yt:'HZp2bk4YHFY'},
{nombre:'I Count The Ways',artista:'Nortec Collective: Bostich+FussibIe',anio:'2010',yt:'xdvEZp8r1pg'},
{nombre:'I Disappear',artista:'The Faint',anio:'2004',yt:'1q8eByzJseY'},
{nombre:'I Don\'t Feel Like Dancin\'',artista:'Scissor Sisters',anio:'2005',yt:'4H5I6y1Qvz0'},
{nombre:'I Don\'t Like It, I love It',artista:'Flo Rida Feat. Robin Thicke & Verdine White',anio:'2016',yt:'uuFGbxpLg94'},
{nombre:'I Feel Alive',artista:'CD9',anio:'2016',yt:'AwSpE65PnjY'},
{nombre:'I Feel It Coming',artista:'The Weeknd Feat. Daft Punk',anio:'2017',yt:'qFLhGq0060w'},
{nombre:'I Feel Love',artista:'Blue Man Group',anio:'2003',yt:'0iFBXjRbVl0'},
{nombre:'I Feel So Bad',artista:'Kungs Feat. Ephemerals',anio:'2016',yt:'0SVk3adkchY'},
{nombre:'I Feel You',artista:'Schiller',anio:'2003',yt:'dQlxjSm0qU0'},
{nombre:'I Gotta Feeling',artista:'Black Eyed Peas',anio:'2009',yt:'uSD4vsh1zDA'},
{nombre:'I Kissed a Girl',artista:'Katy Perry',anio:'2008',yt:'tAp9BKosZXs'},
{nombre:'I Love It',artista:'Icona Pop',anio:'2012',yt:'UxxajLWwzqY'},
{nombre:'I Need To Know',artista:'Marc Antony',anio:'1999',yt:'fLVzw9wVd9o'},
{nombre:'I Rave You',artista:'Basto',anio:'2013',yt:'LK2Urb_naAM'},
{nombre:'I Still Haven\'t Found What I\'m Looking For',artista:'U2',anio:'1987',yt:'O_ISAntOom0'},
{nombre:'I Took A Pill In Ibiza (Seeb Remix)',artista:'Mike Posner',anio:'2015',yt:'foE1mO2yM04'},
{nombre:'I Wanna Be Your Toy',artista:'2 Eivissa',anio:'1999',yt:'28yQFnh9iwo'},
{nombre:'I Want To Know What Love Is',artista:'Foreigner',anio:'1984',yt:'raNGeq3_DtM'},
{nombre:'I Want You',artista:'Bob Sinclar Feat. CeCe Rogers',anio:'2014',yt:'_CpnDcQ9J9s'},
{nombre:'I Was Made For Lovin\' You',artista:'Kiss',anio:'1979',yt:'u7isxoTIeYM'},
{nombre:'I Will Survive',artista:'Cake',anio:'1996',yt:'7KJjVMqNIgA'},
{nombre:'Wish You Were Here',artista:'Offer Nissim Feat. Maya',anio:'2007',yt:'sznSvEqmLLg'},
{nombre:'Ich Will',artista:'Rammstein',anio:'2001',yt:'EOnSh3QlpbQ'},
{nombre:'If',artista:'Bread',anio:'1971',yt:'5a_4fBH_7dk'},
{nombre:'If You Don\'t',artista:'ODESZA Feat. Cumulus',anio:'2012',yt:'xSYOzrwaSPo'},
{nombre:'If You Had My Love',artista:'Jennifer Lopez',anio:'1999',yt:'lYfkl-HXfuU'},
{nombre:'Iko Iko',artista:'Belle Stars',anio:'1989',yt:'B1voj6H8CHY'},
{nombre:'I\'ll Fly With You',artista:'Gigi D\'Agostino',anio:'1999',yt:'olkxWNySPdo'},
{nombre:'I\'ll Missing You',artista:'Puff Daddy',anio:'1997',yt:'mM0-ZU8njdo'},
{nombre:'I\'m Like A Bird',artista:'Nelly Furtado',anio:'2000',yt:'roPQ_M3yJTA'},
{nombre:'I\'m Not in Love',artista:'10CC',anio:'1975',yt:'OtBHfxU2wmc'},
{nombre:'Im Still In Love With You',artista:'Sean Paul',anio:'2002',yt:'N5o-N6we0IY'},
{nombre:'I\'m Yours',artista:'Jason Mraz',anio:'2008',yt:'EkHTsc9PU2A'},
{nombre:'Immigrant Song',artista:'Led Zeppelin',anio:'1970',yt:'RlNhD0oS5pk'},
{nombre:'In Da Gadda Da Vida',artista:'Iron Butterfly',anio:'1968',yt:'UIVe-rZBcm4'},
{nombre:'In For The Kill',artista:'La Roux',anio:'2009',yt:'tXtATeQ7GKg'},
{nombre:'In My Arms',artista:'Kylie Minogue',anio:'2007',yt:'Nj6IKIPteuE'},
{nombre:'In The Dark',artista:'DEV',anio:'2012',yt:'mgEixhE3Oms'},
{nombre:'In The End',artista:'Linkin Park',anio:'2000',yt:'eVTXPUF4Oz4'},
{nombre:'In The Night',artista:'The Weeknd',anio:'2015',yt:'2iFa5We6zqw'},
{nombre:'Infinity 2008',artista:'Guru Josh Project',anio:'2008',yt:'w9KnuJZkBjg'},
{nombre:'Infinity 2012',artista:'DJ Antoine Vs. Mad Mark Remix',anio:'2012',yt:'F-aF0c6EiL0'},
{nombre:'Inndia',artista:'Inna',anio:'2013',yt:'hciBxuTRUno'},
{nombre:'Insane In The Brain',artista:'Cypress Hill',anio:'1993',yt:'RijB8wnJCN0'},
{nombre:'Inside the Lines',artista:'Mike Perry Feat. Casso',anio:'2016',yt:'kbYbvDK-HlY'},
{nombre:'Insomnia',artista:'Fail Less',anio:'????',yt:'FCPXWBSr98E'},
{nombre:'Iris',artista:'Goo Goo Dolls',anio:'1998',yt:'NdYWuo9OFAw'},
{nombre:'Is This Love',artista:'Bob Marley Feat. LVNDSCAPE & Bolier',anio:'????',yt:'W32HW5xj0bM'},
{nombre:'It Ain\'t Over Till It\'s Over',artista:'Lenny Kravitz',anio:'1991',yt:'wkURz6H0I0I'},
{nombre:'It Feels So Good',artista:'Sonique',anio:'2000',yt:'fYW1YmfOHIM'},
{nombre:'It\'s In Your Eyes',artista:'Kylie Minogue',anio:'2001',yt:'OjETibEMbJY'},
{nombre:'Jesus Walks',artista:'Kanye West',anio:'2004',yt:'MYF7H_fpc-g'},
{nombre:'Jubel',artista:'Klingande',anio:'2014',yt:'b6vSf0cA9qY'},
{nombre:'Judgement day',artista:'D-Devils',anio:'2001',yt:'r_rBftVrarY'},
{nombre:'Jump',artista:'Flo Rida Feat. Nelly Furtado',anio:'2009',yt:'6JroV6rZPwI'},
{nombre:'Just Give Me A Reason',artista:'P!nk Feat. Nate Ruess',anio:'2012',yt:'OpQFFLBMEPI'},
{nombre:'Just Like A Pill',artista:'P!nk',anio:'2001',yt:'JDKGWaCglRM'},
{nombre:'Just My Imagination',artista:'Cranberries',anio:'1999',yt:'SHoHIL2ABVQ'},
{nombre:'Kalemba',artista:'Buraka Som Sistema',anio:'2008',yt:'OpYR7ilLbfo'},
{nombre:'Kangaroo Court',artista:'Capital Cities',anio:'2013',yt:'CJinWua98NA'},
{nombre:'Kaya',artista:'Androma Feat. Boy Kiss Girl',anio:'2016',yt:'emolLNXI2mI'},
{nombre:'Kids',artista:'Robbie Williams Feat. Kylie Minogue',anio:'2000',yt:'cvn6eYJh-0c'},
{nombre:'King Of The Bongo',artista:'Manu Chao',anio:'1998',yt:'vJMLJVha5sw'},
{nombre:'King Of The Bongo',artista:'Robbie Williams',anio:'2006',yt:'x1MYoKSRezA'},
{nombre:'Kiss',artista:'Gloster',anio:'????',yt:'5htlVcq0JqQ'},
{nombre:'Kiss My Eyes',artista:'Bob Sinclar',anio:'2003',yt:'7aPwOC7cZCo'},
{nombre:'Komodo',artista:'Mauro Picotto',anio:'2000',yt:'UGoBM2TfOao'},
{nombre:'Komodo',artista:'Xookwankii',anio:'2014',yt:'XE16pF5Kkas'},
{nombre:'Kumbala',artista:'La Maldita Vecindad',anio:'1991',yt:'iNKMR5Pr9ZY'},
{nombre:'Kung Fu Fighting',artista:'Fatboy Slim',anio:'????',yt:'vobOK4zbqMs'},
{nombre:'Kung Fu Fighting',artista:'Foo Fighters',anio:'????',yt:'a97YQO3YAJo'},
{nombre:'La Aspirina',artista:'Comando Groovy',anio:'2007',yt:'GR_LhRJUdm0'},
{nombre:'La Carabina de Ambrosio',artista:'Quartz',anio:'????',yt:'4g3ACPYuE-w'},
{nombre:'La Crema',artista:'Big Metra',anio:'2006',yt:'2Q3o8uqi3X4'},
{nombre:'La Isla Bonita 2008',artista:'Alizee',anio:'2008',yt:'YQhYzvB-IWA'},
{nombre:'La La',artista:'Ashlee Simpson',anio:'2004',yt:'1m0LhDiMj8Q'},
{nombre:'La La La',artista:'Naughty Boy Feat. Sam Smith',anio:'2013',yt:'3O1_3zBUKM8'},
{nombre:'La Lola',artista:'Café Quijano',anio:'1999',yt:'ccsUjRhpo_U'},
{nombre:'La Novela',artista:'Fulanito',anio:'1997',yt:'eqHWa0VzzCU'},
{nombre:'La Pachanga',artista:'Vilma Palma e Vampiros',anio:'1992',yt:'aSHDyslQfgc'},
{nombre:'Lady',artista:'Modjo',anio:'2001',yt:'mMfxI3r_LyA'},
{nombre:'Lala Song',artista:'Bob Sinclar & Sugarhill Gang',anio:'2009',yt:'CB1RutFp0Cc'},
{nombre:'Lambada',artista:'Kaoma',anio:'1989',yt:'iyLdoQGBchQ'},
{nombre:'Lamento Boliviano',artista:'Enanitos Verdes',anio:'1994',yt:'l9kXym1doYA'},
{nombre:'L\'Amour Toujours',artista:'Gigi D\'Agostino',anio:'1999',yt:'w15oWDh02K4'},
{nombre:'Latinos',artista:'Proyecto Uno',anio:'1996',yt:'RIqrVE_BPSo'},
{nombre:'Laura',artista:'Scissor Sisters',anio:'2004',yt:'S-0d3cjgfLg'},
{nombre:'LDN',artista:'Lily Allen',anio:'2006',yt:'wmYT79tPvLg'},
{nombre:'Let Me Blow Ya Mine',artista:'Eve',anio:'2001',yt:'Wt88GMJmVk0'},
{nombre:'Let Me Love You',artista:'DJ Snake Feat. Justin Bieber',anio:'2016',yt:'1dlntjOIz1Y'},
{nombre:'Let Me Think About It',artista:'Ida Corr Feat. Fedde Le Grand',anio:'2009',yt:'o35hxpl6XgU'},
{nombre:'Lethal Industry',artista:'Tiësto',anio:'2001',yt:'bgz2SWdKqvQ'},
{nombre:'Let\'s Get It Started',artista:'Black Eyed Peas',anio:'2003',yt:'IKqV7DB8Iwg'},
{nombre:'Let\'s Go Straight To Number One',artista:'Touch And Go',anio:'1999',yt:'bM_7m4vTPng'},
{nombre:'Levels',artista:'Avicii',anio:'2013',yt:'_ovdm2yX4MA'},
{nombre:'Lights',artista:'Ellie Goulding',anio:'2010',yt:'0NKUpo_xKyQ'},
{nombre:'Like A G6',artista:'Far East Movement',anio:'2010',yt:'w4s6H4ku6ZY'},
{nombre:'Like a Stone',artista:'Audioslave',anio:'2002',yt:'7QU1nvuxaMA'},
{nombre:'Linger',artista:'Cranberries',anio:'1993',yt:'G6Kspj3OO0s'},
{nombre:'Lo Haré Por Ti',artista:'Paulina Rubio',anio:'2000',yt:'iX7VQkCj9hI'},
{nombre:'Locked Away',artista:'R. City Feat. Adam Levine',anio:'2015',yt:'6GUm5g8SG4o'},
{nombre:'Loneliness',artista:'Tomcraft',anio:'2003',yt:'3QV8cOmsTdI'},
{nombre:'Loop & Tings Relooped',artista:'Marco V Vs. Jens',anio:'????',yt:'XQC8gjTs7Dg'},
{nombre:'Los Agachados',artista:'La Maldita Vecindad',anio:'2006',yt:'a1ZB3Wbm0ek'},
{nombre:'Lose Yourself',artista:'Eminem',anio:'2002',yt:'_Yhyp-_hX2s'},
{nombre:'Loser',artista:'Beck',anio:'1994',yt:'YgSPaXgAdzE'},
{nombre:'Losing My Religion',artista:'R.E.M.',anio:'1991',yt:'xwtdhWltSIg'},
{nombre:'Lost In Love',artista:'Air Supply',anio:'1979',yt:'peEX6tYyr9o'},
{nombre:'Love',artista:'Zoé',anio:'2003',yt:'q3yJ_yDhNVk'},
{nombre:'Love a First Sight',artista:'Kylie Minogue',anio:'1988',yt:'GWAKLNEVWB0'},
{nombre:'Love Generation',artista:'Bob Sinclar',anio:'2006',yt:'v0NSeysrDYw'},
{nombre:'Love Love Love',artista:'Lenny Kravitz',anio:'2008',yt:'Sf_7v_Od6X4'},
{nombre:'Love Me Again',artista:'John Newman',anio:'2013',yt:'CfihYWRWRTQ'},
{nombre:'Love Me Like You',artista:'Little Mix',anio:'2015',yt:'1WpoKRnoPRU'},
{nombre:'Love Runs Out',artista:'OneRepublic',anio:'2013',yt:'0OWj0CiM8WU'},
{nombre:'Love Today',artista:'Mika',anio:'2007',yt:'AWiccrTB4LM'},
{nombre:'Lsf',artista:'Kasabian',anio:'2004',yt:'yYYp5-mGQRI'},
{nombre:'Lush Life',artista:'Zara Larsson',anio:'2017',yt:'tD4HCZe-tew'},
{nombre:'Mad World',artista:'Gary Jules',anio:'2001',yt:'4N3N1MlvVc4'},
{nombre:'Madness',artista:'Muse',anio:'2012',yt:'Ek0SgwWmF9w'},
{nombre:'Magic Carpet Ride',artista:'Mighty Dub Katz',anio:'1998',yt:'gX2CQqPvnys'},
{nombre:'Make Her Say',artista:'Kanye West',anio:'2009',yt:'AmSV2cim0Qg'},
{nombre:'Mamy Blue',artista:'Pop Tops',anio:'1971',yt:'mk33lQSKnYY'},
{nombre:'Man-Eater',artista:'Nelly Furtado',anio:'2006',yt:'PLolag3YSYU'},
{nombre:'Manto Estelar',artista:'Moenia',anio:'1999',yt:'9-UreFGdzT4'},
{nombre:'Marry You',artista:'Bruno Mars',anio:'2010',yt:'QWfDjwuj7ao'},
{nombre:'Maybe',artista:'Freda',anio:'2007',yt:'QFTkZEUa9nU'},
{nombre:'Meet Her At The Loveparade',artista:'Da Hool',anio:'1997',yt:'KO4y3nkJXDA'},
{nombre:'Meet Me Halfway',artista:'Black Eyed Peas',anio:'2009',yt:'I7HahVwYpwo'},
{nombre:'Men In Black II',artista:'Will Smith',anio:'2002',yt:'1RVRCd6J2NA'},
{nombre:'Mercy',artista:'Duffy',anio:'2008',yt:'y7ZEVA5dy-Y'},
{nombre:'Mexico Let\'s Go',artista:'Conceptos',anio:'1994',yt:'EViZPcCj_wg'},
{nombre:'Mi Agüita Amarilla',artista:'Los Toreros Muertos',anio:'1986',yt:'qTq1i1SdH3o'},
{nombre:'Middle',artista:'DJ Snake Feat. Bipolar Sunshine',anio:'2016',yt:'mOKqNxN4jWM'},
{nombre:'Midnight City',artista:'M83',anio:'2011',yt:'dX3k_QDnzHE'},
{nombre:'Millionaire',artista:'Plastilina Mosh',anio:'2006',yt:'bojBxTg6Z-g'},
{nombre:'Miss You',artista:'Blink 182',anio:'2003',yt:'s1tAYmMjLdY'},
{nombre:'Miss You',artista:'The Rolling Stones',anio:'1978',yt:'KuRxXRuAz-I'},
{nombre:'Missing',artista:'Everything But The Girl',anio:'1994',yt:'Q4sPkS8b62Q'},
{nombre:'Mission Impossible II',artista:'Limp Bizkit',anio:'2000',yt:'NdpP6ynPbiY'},
{nombre:'Move Ya Body',artista:'Nina Sky',anio:'2004',yt:'Z0WTChSuiek'},
{nombre:'Moves Like Jagger',artista:'Maroon 5',anio:'2010',yt:'iEPTlhBmwRg'},
{nombre:'Mr Saxobeat',artista:'Alexandra Stan',anio:'2011',yt:'sS76eS34Y0c'},
{nombre:'Mr. P',artista:'Plastilina Mosh',anio:'1998',yt:'eRuV0VKINto'},
{nombre:'Ms. Jackson',artista:'OutKast',anio:'2000',yt:'MYxAiK6VnXw'},
{nombre:'Murder On The Dance Floor',artista:'Sophie Ellis-Bextor',anio:'2001',yt:'BsISfQAXE60'},
{nombre:'My Drive Thru',artista:'Santogold / Julian Casablancas / N.E.R.D',anio:'2008',yt:'GPZ5fnYFI4Q'},
{nombre:'My Humps',artista:'Black Eyed Peas',anio:'2005',yt:'iEe_eraFWWs'},
{nombre:'My Sacrifice',artista:'Creed',anio:'2001',yt:'O-fyNgHdmLI'},
{nombre:'Nada',artista:'Zoé',anio:'2008',yt:'6ufJw-TccJ8'},
{nombre:'Nalguita',artista:'Plastilina Mosh',anio:'2005',yt:'ouJYP8QvLvw'},
{nombre:'Natural Blues',artista:'Moby',anio:'1999',yt:'SC6-TiN19uE'},
{nombre:'Neandertal',artista:'Zoé',anio:'2008',yt:'pmUOM_1DsA8'},
{nombre:'New Soul',artista:'Yael Naim',anio:'2007',yt:'XgEfYGzojcA'},
{nombre:'New York',artista:'Moby',anio:'2006',yt:'UVQvQhR0LtM'},
{nombre:'Night @ The Black',artista:'Harry \'\'Choo Choo\'\' Romero',anio:'2001',yt:'dO9wdKQxu0g'},
{nombre:'Night Birds',artista:'Shakatak',anio:'1982',yt:'RAEWs36jLkg'},
{nombre:'Night Of Your Life',artista:'David Guetta',anio:'2011',yt:'lYg01llluMM'},
{nombre:'No',artista:'HNNY',anio:'????',yt:'DyUklh1LrZY'},
{nombre:'No Longer Fun',artista:'Rey Pila',anio:'2010',yt:'1UmuLxGgcx8'},
{nombre:'No Milk Today',artista:'Royal Gigolos',anio:'2004',yt:'Muty0wRsH90'},
{nombre:'No One',artista:'Alicia Keys',anio:'2007',yt:'rywUS-ohqeE'},
{nombre:'No Rain',artista:'Blind Melon',anio:'1992',yt:'qmVn6b7DdpA'},
{nombre:'Nookie',artista:'Limp Bizkit',anio:'1999',yt:'JTMVOzPPtiw'},
{nombre:'Not Alone',artista:'Gianluca Motta feat. Molly (Deadmau5 Remix)',anio:'2008',yt:'BpQVPDn6xB4'},
{nombre:'Not Fair',artista:'Lily Allen',anio:'2009',yt:'fUYaosyR4bE'},
{nombre:'Now We Are Free',artista:'Hans Zimmer, Lisa Gerrard',anio:'2001',yt:'mm-sbOH-nEc'},
{nombre:'Numb / Encore',artista:'Linkin Park Feat. Jay-Z',anio:'2004',yt:'yNPECkESPbU'},
{nombre:'Numb',artista:'U2',anio:'1993',yt:'H2lbiS1fris'},
{nombre:'Nunca Voy A Olvidarte',artista:'Cristian Castro',anio:'1993',yt:'ye6Ef77vKUs'},
{nombre:'Ocean Drive',artista:'Duke Dumont',anio:'2016',yt:'KDxJlW6cxRk'},
{nombre:'Ode To Oi',artista:'TJR',anio:'2014',yt:'YaikPv034Hc'},
{nombre:'Old Yellow Bricks',artista:'Arctic Monkeys',anio:'2007',yt:'dw0cvFJeu7Y'},
{nombre:'On Hold',artista:'The XX',anio:'2017',yt:'blJKoXWlqJk'},
{nombre:'On My Way',artista:'Tiësto Feat. Bright Sparks',anio:'2017',yt:'aojMAMDcB7g'},
{nombre:'On Top Of The World',artista:'Imagine Dragons',anio:'2012',yt:'w5tWYmIOWGk'},
{nombre:'One',artista:'U2',anio:'1991',yt:'BgZ4ammawyI'},
{nombre:'One (Your Name)',artista:'Swedish House Mafia',anio:'2010',yt:'PkQ5rEJaTmk'},
{nombre:'One Dance',artista:'Drake Feat. Wizkid & Kyla',anio:'2016',yt:'rUz7M0FQNwY'},
{nombre:'One Day / Reckoning Song',artista:'Asaf Avidan Feat. The Mojos',anio:'????',yt:'z2gojFNv6s8'},
{nombre:'One Step Beyond',artista:'Madness',anio:'1979',yt:'N-uyWAe0NhQ'},
{nombre:'One Word',artista:'Kelly Osbourne',anio:'2005',yt:'QXctSjshB1M'},
{nombre:'Oooh',artista:'Sugar Hill & Nytron',anio:'2015',yt:'6-LYex8WzM0'},
{nombre:'Open Wide',artista:'Calvin Harris ft. Big Sean',anio:'2014',yt:'zVzhpkFBFP8'},
{nombre:'Ordinary World',artista:'Duran Duran',anio:'1993',yt:'TreNe5D8OXE'},
{nombre:'Otherside',artista:'Red Hot Chili Peppers',anio:'1999',yt:'rn_YodiJO6k'},
{nombre:'Outside World',artista:'Sunbeam',anio:'1997',yt:'BrUX0FOPj0Y'},
{nombre:'Oye Mi Canto',artista:'Daddy-Yankee',anio:'2005',yt:'d2rSOaz0X9Q'},
{nombre:'Paint It, Black',artista:'The Rolling Stones',anio:'1966',yt:'O4irXQhgMqg'},
{nombre:'Paper Aeroplane',artista:'Francesco Rossi',anio:'2013',yt:'ZVQ_cQq5buE'},
{nombre:'Paper Planes',artista:'M.I.A.',anio:'2007',yt:'ewRjZoRtu0Y'},
{nombre:'Papercut',artista:'Linkin Park',anio:'2000',yt:'vjVkXlxsO8Q'},
{nombre:'Paris',artista:'The Chainsmokers',anio:'2017',yt:'fRNkQH4DVg8'},
{nombre:'Party All The Time',artista:'Sharam',anio:'2007',yt:'d3H0d_0pqOI'},
{nombre:'Party Like A Russian',artista:'Robbie Williams',anio:'2016',yt:'MdYGQ7B0Vew'},
{nombre:'Peanut Butter Jelly',artista:'Galantis',anio:'2015',yt:'4jBDnYE1WjI'},
{nombre:'Peligroso Pop',artista:'Plastilina Mosh',anio:'2003',yt:'zE7woxcB35s'},
{nombre:'Penso Positivo',artista:'Jovanotti',anio:'1994',yt:'PC9tgxm9BMM'},
{nombre:'Perhaps, Perhaps, Perhaps',artista:'Cake',anio:'1996',yt:'HWgUBFOCxB0'},
{nombre:'Pervert Pop Song',artista:'Plastilina Mosh',anio:'2008',yt:'PN0u3mzAwj8'},
{nombre:'Phatt Bass',artista:'Warp Brothers vs. Aquagen',anio:'2000',yt:'EGxY1GrXYRw'},
{nombre:'Phatt Bass 2016',artista:'Wolfpack & Warp Brothers',anio:'2016',yt:'xM1K4KwO1uA'},
{nombre:'Phonography',artista:'Britney Spears',anio:'2008',yt:'1SHnbI4YYaQ'},
{nombre:'Photograph',artista:'Ed Sheeran',anio:'2014',yt:'nSDgHBxUbVQ'},
{nombre:'Photograph',artista:'Ed Sheeran (Felix Jaehn Remix)',anio:'2014',yt:'63KRkw8f1rM'},
{nombre:'Pictures',artista:'Timo Maas Feat. Brian Molko',anio:'2005',yt:'dUazp5FC7c0'},
{nombre:'PILLOWTALK',artista:'ZAYN',anio:'2016',yt:'C_3d6GntKbk'},
{nombre:'Played A Live',artista:'Safri Duo',anio:'2001',yt:'IksRDCMYnn8'},
{nombre:'Police Truck',artista:'Dead Kennedys',anio:'1978',yt:'PScmRiaZhwk'},
{nombre:'Porcelain',artista:'Moby',anio:'1999',yt:'FAYHTES4whs'},
{nombre:'Prayer In C',artista:'Lilly Wood & The Prick and Robin Schulz',anio:'2014',yt:'fiore9Z5iUg'},
{nombre:'Price Tag',artista:'Jessie J Feat. B.o.B',anio:'2011',yt:'qMxX-QOV9tI'},
{nombre:'Princess Of China',artista:'Coldplay Feat. Rihanna',anio:'2011',yt:'1Uw6ZkbsAH8'},
{nombre:'Pump It',artista:'Black Eyed Peas',anio:'2005',yt:'ZaI2IlHwmgQ'},
{nombre:'Pumped Up Kicks',artista:'Foster The People',anio:'2011',yt:'SDTZ7iX4vTQ'},
{nombre:'Pumpin Blood',artista:'NONONO',anio:'2014',yt:'3j4I0PqNzKE'},
{nombre:'Pure Morning',artista:'Placebo',anio:'1998',yt:'DHQngnnHE_0'},
{nombre:'Quédate, Cariño Mio',artista:'Luisa Fernanda',anio:'????',yt:'Mu7zfo7R5P8'},
{nombre:'Quiéreme Mucho',artista:'Ely Guerra',anio:'2004',yt:'xpiwJdWVrpY'},
{nombre:'Quisiera Ser Un Pez',artista:'Juan Luis Guerra',anio:'1990',yt:'C5Yvzz7Iy4s'},
{nombre:'Radio',artista:'Sylvan Esso',anio:'2017',yt:'6LEmDEZVa5g'},
{nombre:'Radio Ga Ga',artista:'Queen',anio:'1984',yt:'azdwsXLmrHE'},
{nombre:'Raging',artista:'Kygo Feat. Kodaline',anio:'2016',yt:'ZWyktWYW3ZM'},
{nombre:'Rain Fall Down',artista:'The Rolling Stones',anio:'2005',yt:'SvvJbxl4Vmk'},
{nombre:'Rainin in Paradize',artista:'Manu Chao',anio:'2007',yt:'AewP_ZelObo'},
{nombre:'Rap Da Armas',artista:'Cidinho & Doca',anio:'2009',yt:'ZthNYozVwNM'},
{nombre:'Rapture',artista:'IIO',anio:'2005',yt:'on8DJBt07eU'},
{nombre:'Ready 2 Go',artista:'Martin Solveig Feat. Kele',anio:'2011',yt:'5A44N_ewyTU'},
{nombre:'Ready For The Floor',artista:'Hot Chip',anio:'2008',yt:'8Cxry9cLFQI'},
{nombre:'Ready, Steady, Go',artista:'Paul Oakenfold',anio:'2002',yt:'MSv3Oez4O-4'},
{nombre:'Reality',artista:'Lost Frequencies Feat. Janieck Devy',anio:'2016',yt:'ilw-qmqZ5zY'},
{nombre:'Rehab',artista:'Amy Winehouse',anio:'2006',yt:'KUmZp8pR1uc'},
{nombre:'Remember',artista:'Summerlove',anio:'????',yt:'zb1BpMjxy8M'},
{nombre:'Reptile',artista:'Citizens!',anio:'2012',yt:'wA0lYaekxxk'},
{nombre:'Reptilia',artista:'The Strokes',anio:'2003',yt:'b8-tXG8KrWs'},
{nombre:'Resurrection',artista:'PPK',anio:'2002',yt:'Rce8QnuFRVk'},
{nombre:'Return 2 Iberia',artista:'Jose "Spinnin" Cortes',anio:'2008',yt:'5rZCpHxWvRk'},
{nombre:'Return of the Tres',artista:'Delinquent Habits',anio:'2000',yt:'mX1xyxWkmw0'},
{nombre:'Right Now (Na Na Na)',artista:'Akon',anio:'2008',yt:'vIaH35-MLsk'},
{nombre:'Ringo',artista:'Joris Voorn',anio:'2014',yt:'myCN7WrxGuQ'},
{nombre:'Rise Up',artista:'Yves LaRock',anio:'2008',yt:'zoMYU_nOGNg'},
{nombre:'RIVA (Restart The Game)',artista:'Klingande Feat. Broken Back',anio:'2015',yt:'R1e2nAeA69U'},
{nombre:'Robot Rock',artista:'Daft Punk',anio:'2005',yt:'sFZjqVnWBhc'},
{nombre:'Rock That Body',artista:'Black Eyed Peas',anio:'2009',yt:'nmnjL26OBcY'},
{nombre:'Rockafeller Skank',artista:'Fatboy Slim',anio:'1998',yt:'FMrIy9zm7QY'},
{nombre:'Rollin\'',artista:'Limp Bizkit',anio:'2000',yt:'RYnFIRc0k6E'},
{nombre:'Royals',artista:'Lorde',anio:'2013',yt:'nlcIKh6sBtc'},
{nombre:'Rumors',artista:'Pep & Rash',anio:'2015',yt:'Cif8IcBwoTk'},
{nombre:'Runaway',artista:'Del Shannon',anio:'1961',yt:'_yIaelSVhyM'},
{nombre:'Runaway (U & I)',artista:'Galantis',anio:'2015',yt:'5XR7naZ_zZA'},
{nombre:'Runaway Train',artista:'Soul Asylum',anio:'1992',yt:'NRtvqT_wMeY'},
{nombre:'Runnin\' (Lose It All)',artista:'Naughty Boy Feat. Beyoncé, Arrow Benjamin',anio:'2009',yt:'eJSik6ejkr0'},
{nombre:'Sabotage',artista:'Beastie Boys',anio:'1994',yt:'z5rRZdiu1UE'},
{nombre:'Sadeness, Part 1',artista:'Enigma',anio:'1990',yt:'4F9DxYhqmKw'},
{nombre:'Safe And Sound',artista:'Capital Cities',anio:'2013',yt:'47dtFZ8CFo8'},
{nombre:'Samba Pa Ti',artista:'Carlos Santana',anio:'1974',yt:'j5AUm_xaE9A'},
{nombre:'Sandstorm',artista:'Darude',anio:'2001',yt:'y6120QOlsfU'},
{nombre:'Satisfaction – In Da Club',artista:'Benny Benassi Vs 50 Cent',anio:'????',yt:'Mbl8MEq2iLg'},
{nombre:'Saturday Night',artista:'The Underdog Project',anio:'2002',yt:'4XIYK_JzFnQ'},
{nombre:'Say It Right',artista:'Nelly Furtado',anio:'2006',yt:'6JnGBs88sL0'},
{nombre:'Say Say Say [2015 Remix]',artista:'Paul McCartney Feat. Michael Jackson',anio:'2015',yt:'Hq5KAdWJiWY'},
{nombre:'Say You\'ll Be There',artista:'Spice Girls',anio:'1996',yt:'9ro0FW9Qt-4'},
{nombre:'Scatman World',artista:'Scatman',anio:'1995',yt:'Y2mRA03dWUI'},
{nombre:'Scream & Shout',artista:'will.i.am Feat. Britney Spears',anio:'2013',yt:'kYtGl1dX5qI'},
{nombre:'Seasons In The Sun',artista:'Terry Jacks',anio:'1974',yt:'rhQ13geD2OA'},
{nombre:'Secret Smile',artista:'Semisonic',anio:'1998',yt:'kryV3E4QKGk'},
{nombre:'Seeya',artista:'Deadmau5 Feat. Colleen D\'Agostino',anio:'2014',yt:'8jL2DPylmhE'},
{nombre:'Seven Nation Army',artista:'The White Stripes',anio:'2003',yt:'0J2QdDbelmY'},
{nombre:'Sexercize ',artista:'Kylie Minogue',anio:'2014',yt:'j3VjJKKVNew'},
{nombre:'Sexy And I Know It',artista:'LMFAO',anio:'2011',yt:'wyx6JDQCslE'},
{nombre:'Sexy Boy',artista:'Air',anio:'1998',yt:'lC6vZOgYduk'},
{nombre:'Sexy Dance',artista:'Paulina Rubio',anio:'2000',yt:'ji8c2MOHh6g'},
{nombre:'Sexy Lady',artista:'Shaggy',anio:'2002',yt:'Gcg__eDktgY'},
{nombre:'She Won\'t Let Me Fuck',artista:'Afroman',anio:'2001',yt:'OOBnVfRaeSw'},
{nombre:'Shed A Light',artista:'Robin Schulz & David Guetta & Cheat Codes',anio:'2017',yt:'vdI0JLVhdYc'},
{nombre:'She\'s a Lady',artista:'Tom Jones',anio:'1971',yt:'gvmyTZEqlo8'},
{nombre:'Shine On',artista:'R.I.O.',anio:'2011',yt:'OhLOOdI23bE'},
{nombre:'Shots',artista:'Imagine Dragons',anio:'2015',yt:'qQrgto184Tk'},
{nombre:'Shout',artista:'Tears For Fears',anio:'1985',yt:'Ye7FKc1JQe4'},
{nombre:'Shut Up',artista:'Black Eyed Peas',anio:'2003',yt:'KRzMtlZjXpU'},
{nombre:'Shut Up And Let Me Go',artista:'The Ting Tings',anio:'2008',yt:'tolm-07if3c'},
{nombre:'Si Tú No Vuelves',artista:'Miguel Bose y Shakira',anio:'2007',yt:'tHjAODz6TS0'},
{nombre:'Si Tú Te Atreves',artista:'Luis Miguel',anio:'2008',yt:'2kSmFVhq2ww'},
{nombre:'Sign of the Times',artista:'Harry Styles',anio:'2017',yt:'qN4ooNx77u0'},
{nombre:'Silence',artista:'Gigi D\'Agostino',anio:'2004',yt:'d4Uj96RBprE'},
{nombre:'Silver Screen',artista:'Felix da Housecat',anio:'2001',yt:'n_MLgWpiXEU'},
{nombre:'Sin Tu Amor (Mis Ojos Lloran Por Ti)',artista:'Big Boy',anio:'1996',yt:'fTwZVA6uBl4'},
{nombre:'Sing',artista:'Ed Sheeran',anio:'2014',yt:'tlYcUqEPN58'},
{nombre:'Sing',artista:'Travis',anio:'2001',yt:'eYO1-gGWJyo'},
{nombre:'Sing it back',artista:'Moloko',anio:'1998',yt:'pbTNZN6m0HM'},
{nombre:'Sit Still, Look Pretty',artista:'Daya',anio:'2016',yt:'uPHKkewD1G0'},
{nombre:'Slippin',artista:'Quadron',anio:'2010',yt:'JIDQxYd83z0'},
{nombre:'Slow',artista:'Kylie Minogue',anio:'2003',yt:'Omrp4QR_Rpo'},
{nombre:'Smack My Bitch Up',artista:'The Prodigy',anio:'1997',yt:'2wVOX2RWSDI'},
{nombre:'Smells Like A Teen Spirit',artista:'Nirvana',anio:'1991',yt:'hTWKbfoikeg'},
{nombre:'Smile',artista:'Lily Allen',anio:'2006',yt:'0WxDrVUrSvI'},
{nombre:'Smooth',artista:'Carlos Santana Feat. Rob Thomas',anio:'1999',yt:'6Whgn_iE5uc'},
{nombre:'So Happy Together',artista:'The Turtles',anio:'1967',yt:'P74YRczb84Q'},
{nombre:'So What',artista:'P!nk',anio:'2008',yt:'FJfFZqTlWrQ'},
{nombre:'Someday',artista:'The Strokes',anio:'2001',yt:'knU9gRUWCno'},
{nombre:'Somethin\' Stupid',artista:'Robbie Williams Feat. Nicole Kidman',anio:'2001',yt:'f43nR8Wu_1Y'},
{nombre:'Something',artista:'Lasgo',anio:'2002',yt:'G0M703prHw4'},
{nombre:'Something I Need',artista:'OneRepublic',anio:'2013',yt:'qKCGBgOgp08'},
{nombre:'Something New',artista:'Faul',anio:'2008',yt:'JuPlQSNz_Ts'},
{nombre:'Sonnentanz (Sun Don\'t Shine)',artista:'Klangkarussell Feat. Will Heard',anio:'2014',yt:'79YDgv_zWA4'},
{nombre:'Sordid Affair (Maceo Plex Remix)',artista:'Royksopp',anio:'????',yt:'Ps8OI4Hepzo'},
{nombre:'Soun Tha Mi Primer Amor',artista:'Kinky',anio:'2002',yt:'o_wvxbu3vWg'},
{nombre:'Space',artista:'Micha Moor',anio:'2008',yt:'J_9kAkK6S78'},
{nombre:'Space Jam',artista:'Quad City DJ\'s',anio:'1996',yt:'J9FImc2LOr8'},
{nombre:'Spanish Girl',artista:'Zona Rika',anio:'2003',yt:'5veaRES_Yzs'},
{nombre:'Special K',artista:'Placebo',anio:'2000',yt:'M9_OhjPrNpg'},
{nombre:'Special Needs',artista:'Placebo',anio:'2003',yt:'HClZwFNNMKs'},
{nombre:'Speedcats',artista:'Speedcats Feat. Owen Jarvis',anio:'2006',yt:'hdE3lrfTGmM'},
{nombre:'Speeding Cars',artista:'Walking On Cars',anio:'2016',yt:'w5h4yJ-BpL4'},
{nombre:'Stand By Me',artista:'John Lennon',anio:'1975',yt:'PIJ0TjF4euQ'},
{nombre:'Star Guitar',artista:'Chemical Brothers',anio:'2002',yt:'0S43IwBF0uM'},
{nombre:'Starry Eyed Surprise',artista:'Crazy Town',anio:'2002',yt:'XRAUKrImMrs'},
{nombre:'Stayin\' Alive',artista:'Bee Gees',anio:'1977',yt:'I_izvAbhExY'},
{nombre:'Stealing Time',artista:'Above & Beyond',anio:'2007',yt:'vce2lifDJ-s'},
{nombre:'Stereo Love',artista:'Edward Maya',anio:'2009',yt:'p-Z3YrHJ1sU'},
{nombre:'Stole The Show',artista:'Kygo Feat. Parson James',anio:'2016',yt:'BgfcToAjfdc'},
{nombre:'Stolen Dance',artista:'Milky Dance',anio:'2013',yt:'iX-QaNzd-0Y'},
{nombre:'Stolen Dance (Embody Remix)',artista:'Milky Chance',anio:'????',yt:'z7Bjasi12mE'},
{nombre:'Stop Crying Your Heart Out',artista:'Oasis',anio:'2002',yt:'dhZUsNJ-LQU'},
{nombre:'Stranger',artista:'Hilary Duff',anio:'2007',yt:'MyShkaAwbR8'},
{nombre:'StreamLine',artista:'Newton',anio:'1994',yt:'IjvL-BgNv_Q'},
{nombre:'Strict Machine',artista:'Goldfrapp',anio:'2003',yt:'YeawPUpTHJA'},
{nombre:'Stronger',artista:'Kanye West',anio:'2007',yt:'PsO6ZnUZI0g'},
{nombre:'Sugar',artista:'Robin Schulz Feat. Francesco Yates',anio:'2015',yt:'bvC_0foemLY'},
{nombre:'Summertime Sadness',artista:'Lana Del Rey',anio:'2012',yt:'nVjsGKrE6E8'},
{nombre:'Sun Goes Down',artista:'Robin Schulz',anio:'2014',yt:'Mo4cmTaEDIk'},
{nombre:'Sunny Days',artista:'Armin van Buuren Feat. Josh Cumbee',anio:'2017',yt:'Nt4fp43U2ys'},
{nombre:'Superstylin\'',artista:'Groove Armada',anio:'2001',yt:'_kE0pxRkMtQ'},
{nombre:'Survival',artista:'Muse',anio:'2012',yt:'jkhVjm9iGFc'},
{nombre:'Suspicious Minds',artista:'Elvis Presley',anio:'1969',yt:'SBmAPYkPeYU'},
{nombre:'Sweat',artista:'Snoop Dogg vs. David Guetta',anio:'2011',yt:'KnEXrbAQyIo'},
{nombre:'Sweet Child Of Me',artista:'Guns and Roses',anio:'1987',yt:'1w7OgIMMRc4'},
{nombre:'Sweet Harmony',artista:'The Beloved',anio:'1993',yt:'8-AcuIOFmIs'},
{nombre:'Sympathy For The Devil',artista:'The Rolling Stones',anio:'1968',yt:'vBecM3CQVD8'},
{nombre:'Take Me',artista:'Tiësto',anio:'2014',yt:'IP8OVYyuC60'},
{nombre:'Take Me To Church',artista:'Hozier',anio:'2014',yt:'PVjiKRfKpPI'},
{nombre:'Take Me To Church',artista:'Kiesza',anio:'2014',yt:'kwxIFk3tZSI'},
{nombre:'Take Over Control',artista:'Afrojack Feat. Eva Simons',anio:'2010',yt:'TUoOcDGMgT4'},
{nombre:'Talk',artista:'DJ Snake Feat. George Maple',anio:'2016',yt:'JvtrXVWSREs'},
{nombre:'Tango To Evora',artista:'Consoul Trainin & Pink Noisy Feat. Anastasia Zannis',anio:'2011',yt:'f9rUTAwP5Qk'},
{nombre:'Te Lo Pido Por Favor',artista:'Jaguares',anio:'2002',yt:'OvtoekZmx30'},
{nombre:'Te Soñé (Unplugged)',artista:'Zoé',anio:'2011',yt:'HJqlA_HTEU8'},
{nombre:'Team',artista:'Lorde',anio:'2013',yt:'f2JuxM-snGc'},
{nombre:'Tears',artista:'Clean Bandit Feat. Louisa Johnson',anio:'2016',yt:'dc-nyGo0aC8'},
{nombre:'Teenagers',artista:'My Chemical Romance',anio:'2006',yt:'k6EQAOmJrbw'},
{nombre:'Tell Me',artista:'Andre Crom Feat. David August',anio:'2000',yt:'777RUjSUmbk'},
{nombre:'Tell Me Baby',artista:'Red Hot Chili Peppers',anio:'2006',yt:'oDNcL1VP3rY'},
{nombre:'Tell Me Why',artista:'Paul Van Dyk',anio:'2000',yt:'IJSDQWtYlIw'},
{nombre:'Tell Me Why',artista:'Super Mode',anio:'2010',yt:'zTDeEJyCmNA'},
{nombre:'Thank You',artista:'Dido',anio:'1999',yt:'1TO48Cnl66w'},
{nombre:'That\'s Not My Name',artista:'The Ting Tings',anio:'2008',yt:'v1c2OfAzDTI'},
{nombre:'The 6th Gate',artista:'D-Devils',anio:'2001',yt:'2JVNNRmxupo'},
{nombre:'The Bad Touch',artista:'Bloodhound Gang',anio:'1999',yt:'xat1GVnl8-k'},
{nombre:'The Chamber',artista:'Lenny Kravitz',anio:'2014',yt:'jAHlQ77lm10'},
{nombre:'The Dark Of The Matinée',artista:'Franz Ferdinand',anio:'2004',yt:'cKyG1dRoDlA'},
{nombre:'The Distance',artista:'Cake',anio:'1996',yt:'F_HoMkkRHv8'},
{nombre:'The Fear',artista:'Lily Allen',anio:'2009',yt:'q-wGMlSuX_c'},
{nombre:'The Fox',artista:'Ylvis',anio:'2013',yt:'jofNR_WkoCE'},
{nombre:'The Girl Is Mine',artista:'99 Souls Feat. Destiny\'s Child & Brandy',anio:'2011',yt:'BMaT2nGaEVg'},
{nombre:'The Launch',artista:'DJ Jean',anio:'1998',yt:'Mu0cE9RgK5M'},
{nombre:'The Man Who Sold The World',artista:'Nirvana',anio:'1994',yt:'fregObNcHC8'},
{nombre:'The Mission',artista:'DJ Tomcraft',anio:'2001',yt:'iURpzdvj2Ns'},
{nombre:'The Muzik',artista:'DJ Luis Alvarado',anio:'2011',yt:'5GNE51G207g'},
{nombre:'The Perfect Life',artista:'Moby',anio:'2013',yt:'t3ZDqe5j4q8'},
{nombre:'The Power of Bhangra',artista:'Snap vs. Motivo',anio:'2003',yt:'CkTKMEBCYiY'},
{nombre:'The Promise',artista:'When in Rome',anio:'1988',yt:'5HI_xFQWiYU'},
{nombre:'The Salmon Dance',artista:'Chemical Brothers',anio:'2007',yt:'dDj7DuHVV9E'},
{nombre:'The Things That You Say',artista:'Cicada',anio:'2006',yt:'PT3B1EN4rXc'},
{nombre:'The Time (Dirty Bit)',artista:'Black Eyed Peas',anio:'2010',yt:'JwQZQygg3Lk'},
{nombre:'The Wall',artista:'Pink Floyd',anio:'1979',yt:'YR5ApYxkU-U'},
{nombre:'The World Is Mine',artista:'David Guetta',anio:'2004',yt:'QSwilU0kJF0'},
{nombre:'There Is No Other Time',artista:'Klaxons',anio:'2014',yt:'kzvipIMj9NM'},
{nombre:'This Is The New Shit',artista:'Marilyn Manson',anio:'2003',yt:'u21aTl7lmHw'},
{nombre:'This Love',artista:'Maroon 5',anio:'2002',yt:'XPpTgCho5ZA'},
{nombre:'This Picture',artista:'Placebo',anio:'2003',yt:'x7mOxdEDNn8'},
{nombre:'Thong Song',artista:'Sisqo',anio:'1999',yt:'Oai1V7kaFBk'},
{nombre:'Throw Your Hands Up (Dancar Kuduro)',artista:'Qwote Feat. Pitbull & Lucenzo',anio:'2010',yt:'cp0zCNQViEk'},
{nombre:'Thunder',artista:'Imagine Dragons',anio:'2017',yt:'fKopy74weus'},
{nombre:'Tie A Yellow Ribbon Round The Old Oak Tree',artista:'Tony Orlando & Dawn',anio:'1973',yt:'7NCZ4l8FCFc'},
{nombre:'Tik Tok',artista:'Ke$ha',anio:'2010',yt:'iP6XpLQM2Cs'},
{nombre:'Till The Sky Falls Down',artista:'Dash Berlin',anio:'2009',yt:'hIyPvvWCYAI'},
{nombre:'Timebomb',artista:'Kylie Minogue',anio:'2015',yt:'zL2wGYCINwY'},
{nombre:'Tired Being',artista:'Phonogenic',anio:'2012',yt:'V9vre-b-Fag'},
{nombre:'To the Moon and Back',artista:'Savage Garden',anio:'1997',yt:'HCm6gRHINqA'},
{nombre:'To The Other Side',artista:'The Doors',anio:'1967',yt:'6BIjCW2_Uik'},
{nombre:'Toca\'s Miracle',artista:'Fragma',anio:'2001',yt:'Q7mwuUuQ5Ws'},
{nombre:'Tokyo Drift',artista:'Teriyaki Boyz',anio:'2006',yt:'iuJDhFRDx9M'},
{nombre:'Tomo Para No Enamorarme',artista:'Bersuit Vergarabat',anio:'1998',yt:'mRb9PjPJU1c'},
{nombre:'Torn',artista:'Natalie Imbruglia',anio:'1997',yt:'VV1XWJN3nJo'},
{nombre:'Touch Me',artista:'Rui Da Silva Feat. Cassandra',anio:'2011',yt:'3FkApmj8K1M'},
{nombre:'Toxicity',artista:'System Of A Down',anio:'2001',yt:'64FrYGRrKVY'},
{nombre:'Traffic',artista:'Tiësto',anio:'2004',yt:'wXTgtFnY0Lw'},
{nombre:'Triste Cancion',artista:'El Tri',anio:'1984',yt:'tHe1Nsetr_A'},
{nombre:'Truly Madly Deeply',artista:'Savage Garden',anio:'1997',yt:'WQnAxOQxQIU'},
{nombre:'Try',artista:'P!nk',anio:'2012',yt:'yTCDVfMz15M'},
{nombre:'Tsunami',artista:'DVBBS & Borgeous',anio:'2013',yt:'0EWbonj7f18'},
{nombre:'Tu es Foutu',artista:'Ingrid',anio:'2003',yt:'HfP8lVfbg5w'},
{nombre:'Tu Y Yo Somos Uno Mismo',artista:'Timbiriche',anio:'1988',yt:'TAAqD3OZsMA'},
{nombre:'Tú, Tú, Tú',artista:'La Nueva Banda Timbiriche',anio:'2007',yt:'bMM6pl9r2jk'},
{nombre:'Tubthumping',artista:'Chumbawamba',anio:'1997',yt:'2H5uWRjFsGc'},
{nombre:'Turn Down for What',artista:'DJ Snake, Lil Jon',anio:'2013',yt:'HMUDVMiITOU'},
{nombre:'Turn Off The Light',artista:'Nelly Furtado',anio:'2000',yt:'kOL7aeIDruA'},
{nombre:'Umbrella',artista:'Base-Balls',anio:'2009',yt:'URxzu8EFBVY'},
{nombre:'Un Momento',artista:'Inna',anio:'2011',yt:'0nQE0LGBzKA'},
{nombre:'Unbelievable',artista:'EMF',anio:'1991',yt:'R63gYHIgaB0'},
{nombre:'Unchained Melody',artista:'Righteous Brothers',anio:'1965',yt:'zrK5u5W8afc'},
{nombre:'Universally Speaking',artista:'Red Hot Chili Peppers',anio:'2002',yt:'CoOibAstPJ4'},
{nombre:'Waiting For Love',artista:'Avicii',anio:'2015',yt:'cHHLHGNpCSA'},
{nombre:'Wake up Call',artista:'Maroon 5',anio:'2007',yt:'dkQ0OJ5Byls'},
{nombre:'Walk',artista:'Foo Fighters',anio:'2011',yt:'4PkcfQtibmU'},
{nombre:'Wannabe',artista:'Spice Girls',anio:'1996',yt:'gJLIiF15wjQ'},
{nombre:'Warm',artista:'SG Lewis',anio:'2015',yt:'BSKimd9EX7s'},
{nombre:'Was a Time',artista:'Whigfield',anio:'2007',yt:'5L3iRqf1xgM'},
{nombre:'Wasted',artista:'Tiësto Feat. Matthew Koma',anio:'2014',yt:'AmEIemQfk34'},
{nombre:'Watch Out',artista:'Alex Gaudino',anio:'2008',yt:'hJOiCsL6eD0'},
{nombre:'We Are All Made of Stars',artista:'Moby',anio:'2002',yt:'x1rFAaAKpVc'},
{nombre:'We Are The People',artista:'Empire of the Sun',anio:'2008',yt:'a47Y1lCRHlM'},
{nombre:'We Are Young',artista:'Fun. Feat. Janelle Monáe',anio:'2012',yt:'Sv6dMFF_yts'},
{nombre:'We Can\'t Stop',artista:'Miley Cyrus',anio:'2013',yt:'LrUvu1mlWco'},
{nombre:'We Don\'t Talk Anymore',artista:'Charlie Puth Feat. Selena Gomez',anio:'2016',yt:'3AtDnEC4zak'},
{nombre:'Weapon Of Choice',artista:'Fatboy Slim',anio:'2000',yt:'ZM1fkHQP_Pw'},
{nombre:'Welcome To St. Tropez',artista:'DJ Antoine Vs. Timati Feat. Kalenna',anio:'2011',yt:'Kh2FRFhS7QY'},
{nombre:'Well, Well, Well',artista:'Duffy',anio:'2010',yt:'R6UwmJRkjBs'},
{nombre:'Greensleeves',artista:'Henry VIII',anio:'1580',yt:'HTyuW1Q2oxU'},
{nombre:'What Is Love?',artista:'Haddaway (Deepjack & Mr Nu Remix)',anio:'2013',yt:'cb6WpqqN1ww'},
{nombre:'What Is Love?',artista:'Haddaway',anio:'1993',yt:'HEXWRTEbj1I'},
{nombre:'What\'s Up',artista:'4 Non Blondes',anio:'1992',yt:'6NXnxTNIWkc'},
{nombre:'When It\'s Over',artista:'Sugar Ray',anio:'2001',yt:'kqr4ouQ3Uf8'},
{nombre:'When The Sun Comes Down',artista:'R.I.O.',anio:'2011',yt:'RICRlX1HVCA'},
{nombre:'Where Is The Love?',artista:'Black Eyed Peas',anio:'2003',yt:'WpYeekQkAdc'},
{nombre:'White Flag',artista:'Dido',anio:'2003',yt:'j-fWDrZSiZs'},
{nombre:'White Sand',artista:'Sunlounger',anio:'2005',yt:'zlOswfH9Zfw'},
{nombre:'Who Loves The Sun',artista:'Nu Feat. Jo Ke',anio:'????',yt:'nwIqTTRSjKg'},
{nombre:'Wicked Games',artista:'Parra for Cuva Feat. Anna Naklab',anio:'2015',yt:'Vh5j7zDpy-4'},
{nombre:'Wonderwall',artista:'Oasis',anio:'1995',yt:'bx1Bh8ZvH84'},
{nombre:'Word Up',artista:'Korn',anio:'2004',yt:'1q-k-uN73Gk'},
{nombre:'Would I Lie To You',artista:'David Guetta',anio:'2016',yt:'u0pmV7GoTjc'},
{nombre:'Wrong',artista:'Depeche Mode',anio:'2009',yt:'XGRCvIhqWpg'},
{nombre:'Yakety Yak',artista:'The Coasters',anio:'1961',yt:'-cHB3Rbz1OI'},
{nombre:'Yellow',artista:'Coldplay',anio:'2000',yt:'yKNxeF4KMsY'},
{nombre:'Yo No Me Llamo Javier',artista:'Los Toreros Muertos',anio:'1986',yt:'yznk4m5UQsc'},
{nombre:'You Are My Sunshine',artista:'Domino Dancing',anio:'????',yt:'1LYvVN8nQO8'},
{nombre:'You Don\'t Own Me',artista:'Grace Feat. G-Eazy',anio:'2015',yt:'8SeRU_ZPDkE'},
{nombre:'You Only Live Once',artista:'The Strokes',anio:'2006',yt:'pT68FS3YbQ4'},
{nombre:'You Really Got Me Now',artista:'The Kinks',anio:'1964',yt:'-2GmzyeeXnQ'},
{nombre:'Young Folks',artista:'Peter, Bjorn & John',anio:'2006',yt:'iArXv64tCJA'},
{nombre:'Your Love',artista:'Kylie Minogue',anio:'2001',yt:'G49UJRSibyQ'},
{nombre:'Your Love',artista:'Lime',anio:'1981',yt:'o5QbB3-p4pw'},
{nombre:'Youth Of The Nation',artista:'P.O.D.',anio:'2001',yt:'EDKwCvD56kw'},
{nombre:'Zombie',artista:'Cranberries',anio:'1994',yt:'6Ejga4kJUts'},
{nombre:'Bad Liar',artista:'Selena Gomez',anio:'2017',yt:'NZKXkD6EgBk'},
{nombre:'Twenty Years',artista:'Placebo',anio:'2006',yt:'3hTFcwdyWX4'},
{nombre:'Feel It Still',artista:'Portugal. The Man',anio:'2017',yt:'pBkHHoOIIn8'},
{nombre:'True Feeling',artista:'Galantis',anio:'2017',yt:'bB7enz_9ILw'},
{nombre:'You\'re the Voice',artista:'John Farnham',anio:'1986',yt:'tbkOZTSvrHs'},
{nombre:'Ok',artista:'Robin Schulz Feat. James Blunt',anio:'2017',yt:'P9-4xHVc7uk'},
{nombre:'Attention',artista:'Charlie Puth',anio:'2017',yt:'nfs8NYg7yQM'},
{nombre:'Believer',artista:'Imagine Dragons',anio:'2017',yt:'7wtfhZwyrcc'},
{nombre:'Friends',artista:'Justin Bieber Feat. BloodPop®',anio:'2017',yt:'ctfLLsD84vk'},
{nombre:'Dusk Till Dawn',artista:'ZAYN Feat. Sia',anio:'2017',yt:'tt2k8PGm-TI'},
{nombre:'Turn No More',artista:'Public Service Broadcasting Feat. James Dean Bradfield',anio:'2017',yt:'cd6Vffdou1c'},
{nombre:'New Rules',artista:'Dua Lipa',anio:'2017',yt:'k2qgadSvNyU'},
{nombre:'It Wasn\'t Me',artista:'Shaggy',anio:'2000',yt:'2g5Hz17C4is'},
{nombre:'La Miranda',artista:'Band (O) Neon',anio:'2005',yt:'oi0iytO8bhY'},
{nombre:'Pretty Fly',artista:'The Offspring',anio:'1998',yt:'QtTR-_Klcq8'},
{nombre:'Reload',artista:'Sebastian Ingrosso Feat. Tommy Trash & John Martin',anio:'2013',yt:'GuAtcpFQpMw'},
{nombre:'Drops of Jupiter',artista:'Train',anio:'2001',yt:'7Xf-Lesrkuc'},
{nombre:'Samba De Janeiro',artista:'Bellini',anio:'1997',yt:'HAiHEQblKeQ'},
{nombre:'Imitation Of Life',artista:'R.E.M.',anio:'2001',yt:'0vqgdSsfqPs'},
{nombre:'Four To The Floor (Thin White Duke Mix)',artista:'Starsailor',anio:'????',yt:'X9wqR1XhQ3o'},
{nombre:'Dream On',artista:'Aerosmith',anio:'1973',yt:'hHRNSeuvzlM'},
{nombre:'Gnossiennes No.1',artista:'Erik Satie',anio:'1893',yt:'RyFhsG8Ip4E'},
{nombre:'Put Your Lights On',artista:'Carlos Santana Feat. Everlast',anio:'1999',yt:'KCBS5EtszYI'},
{nombre:'A Light That Never Comes',artista:'Linkin Park Feat. Steve Aoki',anio:'2013',yt:'ToHo29kD9Go'},
{nombre:'Fable',artista:'Robert Miles',anio:'1996',yt:'jJHpK0EQ93A'},
{nombre:'1, 2 Step',artista:'Ciara',anio:'2004',yt:'iBHNgV6_znU'},
{nombre:'Kissing Strangers',artista:'DNCE Feat. Nicki Minaj',anio:'2016',yt:'wzZWXrlDj-A'},
{nombre:'Supergirl',artista:'Anna Naklab Feat. Alle Farben & YOUNOTUS',anio:'2015',yt:'31tiWX-8bdc'},
{nombre:'Spybreak!',artista:'Propellerheads',anio:'1998',yt:'iCBL33NKvPA'},
{nombre:'Promises',artista:'The Cranberries',anio:'1999',yt:'hUFPooqKllA'},
{nombre:'Dormir Soñando',artista:'El Gran Silencio',anio:'1998',yt:'73L-91N1Fh8'},
{nombre:'Grace Kelly',artista:'Mika',anio:'2007',yt:'0CGVgAYJyjk'},
{nombre:'Breathe',artista:'Jax Jones Feat. Ina Wroldsen',anio:'2018',yt:'uGhKqb2Ow3E'},
{nombre:'Anywhere',artista:'Rita Ora',anio:'2017',yt:'ksdAs4LBRq8'},
{nombre:'Glue',artista:'Bicep',anio:'2017',yt:'A7ZxRs45tTg'},
{nombre:'Reload',artista:'Sebastian Ingrosso, Tommy Trash, John Martin',anio:'2013',yt:'GuAtcpFQpMw'},
{nombre:'Adagio For Strings',artista:'DJ Tiesto',anio:'2004',yt:'8tIgN7eICn4'},
{nombre:'I Need Your Love',artista:'Calvin Harris Feat. Ellie Goulding',anio:'2012',yt:'AtKZKl7Bgu0'},
{nombre:'I Think I Like It',artista:'Fake Blood',anio:'2010',yt:'g_w7GJBfiYc'},
{nombre:'One Love',artista:'David Guetta Feat. Estelle',anio:'2009',yt:'cQyGYdRqulQ'},
{nombre:'sunset',artista:'Robin Schulz',anio:'2014',yt:'QDS0wRloIG8'},
{nombre:'Dream of You',artista:'Schiller',anio:'2001',yt:'u8uYeHy10ZY'},
{nombre:'In And Out Of Love',artista:'Armin van Buuren Feat. Sharon den Adel',anio:'2008',yt:'syHSXQAQTrI'},
{nombre:'Sad Story (Out Of Luck)',artista:'Merk & Kremont',anio:'2017',yt:'8GotXeCwUnc'},
{nombre:'Break On Through (To The Other Side)',artista:'The Doors',anio:'1967',yt:'-r679Hhs9Zs'},
];
